"""
Transcribes a RENDERED rough-cut output (word-level) as the raw material
for caption authoring. Deliberately transcribes the final output.mp4, not
any transcript from the rough-cut stage -- captions must be timed against
what's actually in the video, and the rough-cut skill's own lesson applies
here too: no transcript is ground truth, always re-check the actual file.

This produces the RAW material only. Turning it into styled, corrected,
well-grouped caption cards (fixing ASR errors via the glossary, deciding
word groupings, flagging highlight terms) is an editorial step done by
reading this output, the same way rough-cut's cutlist.json is hand-built
from a transcript rather than generated by a rules engine.

Usage:
    python make_captions.py <video.mp4> <output_words.json> [--language pl]
"""

import argparse
import json
import sys

from faster_whisper import WhisperModel


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("video")
    parser.add_argument("output_json")
    parser.add_argument("--language", default="pl")
    parser.add_argument("--model", default="large-v3")
    args = parser.parse_args()

    print(f"[make_captions] transcribing {args.video} with {args.model}...", file=sys.stderr)
    model = WhisperModel(args.model, device="cpu", compute_type="int8")
    segments, info = model.transcribe(
        args.video, language=args.language, word_timestamps=True,
        condition_on_previous_text=False,
        compression_ratio_threshold=4.0, log_prob_threshold=-2.0,
        temperature=0.0, beam_size=5,
    )

    words = []
    for seg in segments:
        for w in (seg.words or []):
            words.append({
                "word": w.word.strip(),
                "start": round(w.start, 3),
                "end": round(w.end, 3),
                "score": round(w.probability, 3),
            })

    with open(args.output_json, "w", encoding="utf-8") as f:
        json.dump({"language": args.language, "words": words}, f, ensure_ascii=False, indent=2)

    print(f"[make_captions] wrote {len(words)} words to {args.output_json}", file=sys.stderr)
    low_conf = [w for w in words if w["score"] < 0.6]
    if low_conf:
        print(f"[make_captions] {len(low_conf)} words scored below 0.6 confidence -- worth a second look against the glossary:", file=sys.stderr)
        for w in low_conf:
            print(f"  {w['start']:.2f}s  '{w['word']}'  (score {w['score']:.2f})", file=sys.stderr)


if __name__ == "__main__":
    main()
